export interface ChordPageData {
  slug: string;
  symbol: string;
  frenchName: string;
  root: string;
  quality: 'majeur' | 'mineur';
  notes: string[];
  frenchNotes: string[];
  relatedSlugs: string[];
  description: string;
  faqItems: { q: string; a: string }[];
}

const NOTE_FR: Record<string, string> = {
  C: 'Do', D: 'Ré', E: 'Mi', F: 'Fa', G: 'Sol', A: 'La', B: 'Si',
  'C#': 'Do#', 'Db': 'Ré♭', 'D#': 'Ré#', 'Eb': 'Mi♭',
  'F#': 'Fa#', 'Gb': 'Sol♭', 'G#': 'Sol#', 'Ab': 'La♭',
  'A#': 'La#', 'Bb': 'Si♭',
};

function fr(note: string): string {
  return NOTE_FR[note] ?? note;
}

export const CHORD_PAGES: ChordPageData[] = [
  // ── MAJEURS ────────────────────────────────────────────────────────────────
  {
    slug: 'do-majeur',
    symbol: 'C',
    frenchName: 'Do majeur',
    root: 'C',
    quality: 'majeur',
    notes: ['C', 'E', 'G'],
    frenchNotes: ['Do', 'Mi', 'Sol'],
    relatedSlugs: ['fa-majeur', 'sol-majeur', 'la-mineur', 'mi-mineur'],
    description: 'Accord de Do majeur : notes Do–Mi–Sol, diagramme guitare et piano, doigtés et accords proches.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Do majeur ?', a: 'L\'accord de Do majeur est formé de trois notes : Do (C), Mi (E) et Sol (G). C\'est un accord majeur fondamental, très stable et lumineux.' },
      { q: 'Comment jouer Do majeur à la guitare ?', a: 'Sur une guitare standard, Do majeur se joue en posant l\'index sur la corde de Si (2e frette), le majeur sur la corde de Ré (2e frette) et l\'annulaire sur la corde de La (3e frette). La corde de Mi grave n\'est pas jouée.' },
      { q: 'Do majeur et Do mineur, quelle différence ?', a: 'Do majeur contient Mi naturel, ce qui lui donne un son joyeux et ouvert. Do mineur remplace le Mi par un Mi♭, ce qui crée une sonorité plus sombre et mélancolique.' },
      { q: 'Quels accords s\'enchaînent bien avec Do majeur ?', a: 'Do majeur s\'enchaîne naturellement avec Fa majeur, Sol majeur et La mineur. Ces quatre accords forment la tonalité de Do et permettent de jouer de nombreuses chansons.' },
    ],
  },
  {
    slug: 're-majeur',
    symbol: 'D',
    frenchName: 'Ré majeur',
    root: 'D',
    quality: 'majeur',
    notes: ['D', 'F#', 'A'],
    frenchNotes: ['Ré', 'Fa#', 'La'],
    relatedSlugs: ['sol-majeur', 'la-majeur', 'si-mineur', 'fad-mineur'],
    description: 'Accord de Ré majeur : notes Ré–Fa#–La, diagramme guitare et piano, doigtés complets.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Ré majeur ?', a: 'L\'accord de Ré majeur est composé de Ré (D), Fa# (F#) et La (A). La présence du Fa# lui donne un caractère brillant et énergique.' },
      { q: 'Comment jouer Ré majeur à la guitare ?', a: 'Ré majeur à la guitare : laissez les deux cordes graves à vide, puis posez l\'index sur la corde de Sol (2e frette), le majeur sur la corde de mi aigu (2e frette) et l\'annulaire sur la corde de Si (3e frette).' },
      { q: 'Ré majeur est-il difficile pour un débutant ?', a: 'Ré majeur est l\'un des premiers accords à apprendre. Il ne nécessite que trois doigts sur les trois cordes aiguës, sans barré. Il est souvent parmi les cinq premiers accords travaillés.' },
      { q: 'Dans quelles tonalités trouve-t-on Ré majeur ?', a: 'Ré majeur est l\'accord tonique de la tonalité de Ré. On le retrouve aussi fréquemment dans les tonalités de Sol majeur (accord IV) et La majeur (accord IV inverse).' },
    ],
  },
  {
    slug: 'mi-majeur',
    symbol: 'E',
    frenchName: 'Mi majeur',
    root: 'E',
    quality: 'majeur',
    notes: ['E', 'G#', 'B'],
    frenchNotes: ['Mi', 'Sol#', 'Si'],
    relatedSlugs: ['la-majeur', 'si-majeur', 'do-diese-mineur', 'la-mineur'],
    description: 'Accord de Mi majeur : notes Mi–Sol#–Si, diagramme guitare et piano, le premier accord de guitare à apprendre.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Mi majeur ?', a: 'Mi majeur est formé de Mi (E), Sol# (G#) et Si (B). C\'est l\'un des sons les plus puissants à la guitare car toutes les cordes peuvent être jouées à vide.' },
      { q: 'Pourquoi Mi majeur est-il idéal pour commencer la guitare ?', a: 'Mi majeur utilise toutes les six cordes et permet de jouer les cordes Mi grave et Mi aigu à vide. Avec seulement deux doigts (ou trois), il produit un son très plein et résonnant.' },
      { q: 'Quelle est la différence entre Mi majeur et Mi mineur ?', a: 'Mi mineur retire le Sol# pour le remplacer par un Sol naturel. Mi mineur ne nécessite que deux doigts à la guitare, contre trois pour Mi majeur.' },
      { q: 'Dans quelles chansons entend-on Mi majeur ?', a: 'Mi majeur est omniprésent dans le rock et le blues. On le retrouve dans d\'innombrables progressions en tonalité de Mi, notamment dans le blues en Mi, le rock et le country.' },
    ],
  },
  {
    slug: 'fa-majeur',
    symbol: 'F',
    frenchName: 'Fa majeur',
    root: 'F',
    quality: 'majeur',
    notes: ['F', 'A', 'C'],
    frenchNotes: ['Fa', 'La', 'Do'],
    relatedSlugs: ['do-majeur', 'sib-majeur', 'do-mineur', 're-mineur'],
    description: 'Accord de Fa majeur : notes Fa–La–Do, diagramme guitare (barré) et piano. Guide pour maîtriser le premier barré.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Fa majeur ?', a: 'Fa majeur est composé de Fa (F), La (A) et Do (C). C\'est un accord très commun dans les tonalités de Do, Si♭ et Mi♭.' },
      { q: 'Pourquoi Fa majeur est-il difficile à la guitare ?', a: 'Fa majeur en position ouverte nécessite un barré complet à la première frette : l\'index barre toutes les cordes pendant que les autres doigts forment une forme de Mi. Ce barré est souvent le premier obstacle technique de la guitare.' },
      { q: 'Existe-t-il une alternative au barré pour Fa majeur ?', a: 'Oui : jouez seulement Fa–La–Do sur les 4 cordes aiguës (mini-barré sur les deux premières cordes). Ce n\'est pas aussi plein, mais c\'est plus accessible en début d\'apprentissage.' },
      { q: 'Fa majeur et Do majeur sont-ils liés ?', a: 'Oui, Fa majeur est la sous-dominante (accord IV) de Do majeur. Ce sont deux des accords les plus fréquemment associés, avec Sol majeur, dans la tonalité de Do.' },
    ],
  },
  {
    slug: 'sol-majeur',
    symbol: 'G',
    frenchName: 'Sol majeur',
    root: 'G',
    quality: 'majeur',
    notes: ['G', 'B', 'D'],
    frenchNotes: ['Sol', 'Si', 'Ré'],
    relatedSlugs: ['do-majeur', 're-majeur', 'mi-mineur', 'la-mineur'],
    description: 'Accord de Sol majeur : notes Sol–Si–Ré, diagramme guitare et piano. Un accord essentiel pour folk, pop et rock.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Sol majeur ?', a: 'Sol majeur est formé de Sol (G), Si (B) et Ré (D). Ces trois notes constituent la triade de Sol, la fondation de la tonalité de Sol majeur.' },
      { q: 'Comment doigter Sol majeur à la guitare ?', a: 'La forme la plus courante : annulaire sur Mi grave (3e frette), majeur sur La (2e frette), auriculaire sur Mi aigu (3e frette). Toutes les cordes sonnent. Certains ajoutent un Si sur la corde de Si (3e frette) pour plus de plénitude.' },
      { q: 'Sol majeur est-il adapté aux débutants ?', a: 'Sol majeur est l\'un des premiers accords enseignés car il sonne sur les six cordes ouvertes. Il demande cependant un bon écartement des doigts, ce qui peut prendre quelques jours à maîtriser.' },
      { q: 'Quels accords enchaîner avec Sol majeur ?', a: 'Sol majeur s\'enchaîne parfaitement avec Ré majeur, Do majeur et Mi mineur. Ces combinaisons couvrent d\'innombrables chansons folk et pop.' },
    ],
  },
  {
    slug: 'la-majeur',
    symbol: 'A',
    frenchName: 'La majeur',
    root: 'A',
    quality: 'majeur',
    notes: ['A', 'C#', 'E'],
    frenchNotes: ['La', 'Do#', 'Mi'],
    relatedSlugs: ['re-majeur', 'mi-majeur', 'fad-mineur', 'do-diese-mineur'],
    description: 'Accord de La majeur : notes La–Do#–Mi, diagramme guitare et piano. Indispensable dans le rock, le blues et la country.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de La majeur ?', a: 'La majeur est formé de La (A), Do# (C#) et Mi (E). Le Do# lui donne un caractère brillant qui contraste avec le La mineur.' },
      { q: 'Comment jouer La majeur à la guitare ?', a: 'La majeur se joue en bloquant les cordes de Ré, Sol et Si sur la 2e frette (trois doigts côte à côte, ou barré partiel). Les cordes La grave et Mi sont jouées à vide, la corde de Mi aigu aussi.' },
      { q: 'La majeur est-il utilisé dans le blues ?', a: 'Oui, La majeur est l\'accord I dans le blues en La, l\'une des tonalités les plus populaires pour la guitare. Il s\'enchaîne avec Ré majeur (IV) et Mi majeur (V) dans la progression blues classique.' },
      { q: 'Quelle est la note caractéristique de La majeur ?', a: 'Le Do# est la note qui définit le caractère majeur de l\'accord. En passant à La mineur, ce Do# devient Do naturel, changeant radicalement l\'ambiance.' },
    ],
  },
  {
    slug: 'si-majeur',
    symbol: 'B',
    frenchName: 'Si majeur',
    root: 'B',
    quality: 'majeur',
    notes: ['B', 'D#', 'F#'],
    frenchNotes: ['Si', 'Ré#', 'Fa#'],
    relatedSlugs: ['mi-majeur', 'fad-majeur', 'sold-mineur', 'do-diese-mineur'],
    description: 'Accord de Si majeur : notes Si–Ré#–Fa#, diagramme guitare (barré 2e frette) et piano.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Si majeur ?', a: 'Si majeur est formé de Si (B), Ré# (D#) et Fa# (F#). C\'est un accord brillant souvent joué en barré à la 2e frette de la guitare.' },
      { q: 'Comment jouer Si majeur à la guitare ?', a: 'Si majeur se joue en barré à la 2e frette : l\'index barre les 5 cordes (sauf Mi grave), et les autres doigts forment une forme de La. C\'est la même forme de barré que pour Si♭, mais une frette plus haut.' },
      { q: 'Si majeur est-il difficile pour les débutants ?', a: 'Oui, Si majeur nécessite un barré partiel (5 cordes) à la 2e frette, qui est souvent la position la plus difficile pour un barré. Il est généralement appris après avoir maîtrisé Fa majeur.' },
      { q: 'Dans quelles tonalités trouve-t-on Si majeur ?', a: 'Si majeur est l\'accord tonique de la tonalité de Si. On le retrouve aussi comme accord V dans la tonalité de Mi majeur, et comme accord III dans la tonalité de Sol# mineur.' },
    ],
  },
  {
    slug: 'reb-majeur',
    symbol: 'Db',
    frenchName: 'Ré♭ majeur',
    root: 'Db',
    quality: 'majeur',
    notes: ['Db', 'F', 'Ab'],
    frenchNotes: ['Ré♭', 'Fa', 'La♭'],
    relatedSlugs: ['solb-majeur', 'lab-majeur', 'sib-mineur', 'fa-mineur'],
    description: 'Accord de Ré♭ majeur (Do# majeur) : notes Ré♭–Fa–La♭, diagramme guitare et piano.',
    faqItems: [
      { q: 'Ré♭ majeur et Do# majeur, c\'est le même accord ?', a: 'Oui, Ré♭ (D♭) et Do# (C#) sont deux noms pour la même note et donc le même accord. Ré♭ est utilisé dans les partitions en bémols, Do# dans les partitions en dièses.' },
      { q: 'Quelles notes composent l\'accord de Ré♭ majeur ?', a: 'Ré♭ majeur est formé de Ré♭ (Db), Fa (F) et La♭ (Ab). C\'est la même structure d\'intervalles que tout accord majeur : fondamentale, tierce majeure et quinte juste.' },
      { q: 'Comment jouer Ré♭ majeur à la guitare ?', a: 'Ré♭ majeur se joue en barré à la 4e frette sur la forme de La. L\'index barre les 5 cordes à la 4e frette, avec les autres doigts sur les cordes Ré, Sol, Si à la 6e frette.' },
      { q: 'Ré♭ majeur est-il courant dans la musique populaire ?', a: 'Ré♭ majeur (et son équivalent Do# majeur) est très utilisé dans la pop et le R&B car il sonne bien sur le piano. C\'est la tonalité favorite de nombreux standards de jazz et de ballades pop.' },
    ],
  },
  {
    slug: 'mib-majeur',
    symbol: 'Eb',
    frenchName: 'Mi♭ majeur',
    root: 'Eb',
    quality: 'majeur',
    notes: ['Eb', 'G', 'Bb'],
    frenchNotes: ['Mi♭', 'Sol', 'Si♭'],
    relatedSlugs: ['lab-majeur', 'sib-majeur', 'do-mineur', 'sol-mineur'],
    description: 'Accord de Mi♭ majeur : notes Mi♭–Sol–Si♭, tonalité naturelle du piano et des cuivres.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Mi♭ majeur ?', a: 'Mi♭ majeur est formé de Mi♭ (Eb), Sol (G) et Si♭ (Bb). C\'est l\'accord tonique de la tonalité de Mi♭, très utilisée au piano et dans la musique de jazz.' },
      { q: 'Pourquoi Mi♭ majeur est-il apprécié au piano ?', a: 'Les touches noires donnent une bonne assise aux mains sur le piano. Mi♭ majeur s\'inscrit naturellement dans la gamme de Mi♭ (3 bémols), souvent utilisée pour les ballades.' },
      { q: 'Mi♭ majeur et trompette, quelle relation ?', a: 'La trompette en Si♭ doit transposer de 2 demi-tons. Pour jouer Mi♭ concert, le trompettiste lit et joue Fa majeur. ChordFinder gère cette transposition automatiquement.' },
      { q: 'Comment jouer Mi♭ majeur à la guitare ?', a: 'Mi♭ majeur se joue en barré à la 6e frette sur la forme de La, ou en barré à la 11e frette sur la forme de Mi. En position plus basse, on peut aussi utiliser la 3e frette avec une forme de Do transposée.' },
    ],
  },
  {
    slug: 'solb-majeur',
    symbol: 'Gb',
    frenchName: 'Sol♭ majeur',
    root: 'Gb',
    quality: 'majeur',
    notes: ['Gb', 'Bb', 'Db'],
    frenchNotes: ['Sol♭', 'Si♭', 'Ré♭'],
    relatedSlugs: ['reb-majeur', 'lab-majeur', 'mib-mineur', 'sib-mineur'],
    description: 'Accord de Sol♭ majeur (Fa# majeur) : notes Sol♭–Si♭–Ré♭, diagramme guitare et piano.',
    faqItems: [
      { q: 'Sol♭ majeur et Fa# majeur sont-ils identiques ?', a: 'Oui, Sol♭ (Gb) et Fa# (F#) sont deux noms enharmoniques pour la même hauteur. Sol♭ s\'utilise généralement dans les tonalités à bémols, Fa# dans les tonalités à dièses.' },
      { q: 'Quelles notes composent l\'accord de Sol♭ majeur ?', a: 'Sol♭ majeur est formé de Sol♭ (Gb), Si♭ (Bb) et Ré♭ (Db). La même structure en intervalles que tout accord majeur.' },
      { q: 'Comment jouer Sol♭ majeur à la guitare ?', a: 'Sol♭/Fa# majeur se joue en barré à la 2e frette sur la forme de Mi, ou en barré à la 9e frette sur la forme de La.' },
      { q: 'Sol♭ majeur est-il utilisé dans la musique contemporaine ?', a: 'Fa# majeur (Sol♭) est fréquent dans la pop moderne. Il sonne bien sur des claviers et est utilisé dans de nombreuses ballades pop, notamment associé à des accords comme Si majeur et Do# mineur.' },
    ],
  },
  {
    slug: 'lab-majeur',
    symbol: 'Ab',
    frenchName: 'La♭ majeur',
    root: 'Ab',
    quality: 'majeur',
    notes: ['Ab', 'C', 'Eb'],
    frenchNotes: ['La♭', 'Do', 'Mi♭'],
    relatedSlugs: ['mib-majeur', 'reb-majeur', 'fa-mineur', 'do-mineur'],
    description: 'Accord de La♭ majeur : notes La♭–Do–Mi♭, tonalité des ballades classiques et du jazz.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de La♭ majeur ?', a: 'La♭ majeur est formé de La♭ (Ab), Do (C) et Mi♭ (Eb). Avec 4 bémols à la clé, la tonalité de La♭ est souvent utilisée dans les ballades et le jazz.' },
      { q: 'Comment jouer La♭ majeur à la guitare ?', a: 'La♭ majeur se joue en barré à la 4e frette sur la forme de Mi, ou en barré à la 11e frette sur la forme de La.' },
      { q: 'Pourquoi La♭ majeur est-il populaire dans les ballades ?', a: 'La tonalité de La♭ offre des progressions harmoniques riches avec beaucoup de résonance. Les barres de bémols créent une couleur chaleureuse souvent associée aux émotions profondes en musique.' },
      { q: 'La♭ majeur et les instruments transpositeurs ?', a: 'Pour un saxophone alto (Mi♭), La♭ concert devient Fa majeur sur la partition. Pour une trompette (Si♭), La♭ concert devient Si♭ majeur pour le musicien. ChordFinder calcule tout automatiquement.' },
    ],
  },
  {
    slug: 'sib-majeur',
    symbol: 'Bb',
    frenchName: 'Si♭ majeur',
    root: 'Bb',
    quality: 'majeur',
    notes: ['Bb', 'D', 'F'],
    frenchNotes: ['Si♭', 'Ré', 'Fa'],
    relatedSlugs: ['fa-majeur', 'mib-majeur', 'sol-mineur', 're-mineur'],
    description: 'Accord de Si♭ majeur : notes Si♭–Ré–Fa, tonique naturelle pour trompette Si♭ et clarinette.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Si♭ majeur ?', a: 'Si♭ majeur est formé de Si♭ (Bb), Ré (D) et Fa (F). C\'est l\'accord central de la tonalité de Si♭, très utilisée dans le jazz, le blues et la musique de cuivres.' },
      { q: 'Pourquoi Si♭ majeur est-il naturel pour la trompette ?', a: 'La trompette est accordée en Si♭ : quand elle joue « Do » sur sa partition, elle produit un Si♭ concert. Donc Si♭ concert correspond au « Do » de la trompette — c\'est son accord le plus naturel.' },
      { q: 'Comment jouer Si♭ majeur à la guitare ?', a: 'Si♭ majeur se joue en barré à la 1ère frette sur la forme de La (corde grave muette). C\'est souvent le premier barré que les guitaristes travaillent après Fa majeur.' },
      { q: 'Si♭ majeur est-il un accord de blues ?', a: 'Si♭ majeur est fondamental dans le blues joué par les cuivres. Les big bands jouent souvent en Si♭ ou Mi♭ car ces tonalités sont confortables pour les saxophones et les trompettes.' },
    ],
  },

  // ── MINEURS ────────────────────────────────────────────────────────────────
  {
    slug: 'do-mineur',
    symbol: 'Cm',
    frenchName: 'Do mineur',
    root: 'C',
    quality: 'mineur',
    notes: ['C', 'Eb', 'G'],
    frenchNotes: ['Do', 'Mi♭', 'Sol'],
    relatedSlugs: ['do-majeur', 'mib-majeur', 'sol-mineur', 'lab-majeur'],
    description: 'Accord de Do mineur : notes Do–Mi♭–Sol, diagramme guitare et piano. L\'accord mineur le plus sombre.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Do mineur ?', a: 'Do mineur est formé de Do (C), Mi♭ (Eb) et Sol (G). Le Mi♭ est la tierce mineure qui donne à cet accord son caractère sombre et mélancolique, par opposition au Do majeur (Do–Mi–Sol).' },
      { q: 'Comment jouer Do mineur à la guitare ?', a: 'Do mineur en position standard : la corde Mi aigu est muette. L\'index barre la corde Mi grave à la 3e frette (ou on utilise l\'annulaire), avec les autres doigts sur Mi aigu, Sol et Do.' },
      { q: 'Quelle est la différence entre Do majeur et Do mineur ?', a: 'La seule différence est le Mi : Do majeur contient Mi naturel (son joyeux), Do mineur contient Mi♭ (sonorité sombre). Cette demi-teinte change radicalement l\'ambiance émotionnelle.' },
      { q: 'Do mineur est-il utilisé dans la musique classique ?', a: 'Oui, Do mineur est célèbre grâce à Beethoven (5e symphonie) et Bach. Dans la musique populaire, on le retrouve dans de nombreuses ballades rock et pop dramatiques.' },
    ],
  },
  {
    slug: 're-mineur',
    symbol: 'Dm',
    frenchName: 'Ré mineur',
    root: 'D',
    quality: 'mineur',
    notes: ['D', 'F', 'A'],
    frenchNotes: ['Ré', 'Fa', 'La'],
    relatedSlugs: ['fa-majeur', 'la-majeur', 'do-majeur', 'sol-mineur'],
    description: 'Accord de Ré mineur : notes Ré–Fa–La. L\'accord mineur le plus facile à la guitare pour les débutants.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Ré mineur ?', a: 'Ré mineur est formé de Ré (D), Fa (F) et La (A). Le Fa naturel (au lieu de Fa# dans Ré majeur) donne à cet accord un caractère plus mélancolique.' },
      { q: 'Comment jouer Ré mineur à la guitare ?', a: 'Ré mineur est souvent l\'un des premiers accords mineurs appris : index sur Mi aigu (1re frette), majeur sur Sol (2e frette), annulaire sur Si (3e frette). Les deux cordes graves ne sont pas jouées.' },
      { q: 'Ré mineur est-il difficile par rapport à Ré majeur ?', a: 'Ré mineur est souvent considéré comme plus accessible que Ré majeur car les doigts se positionnent de manière plus intuitive. C\'est un excellent accord pour introduire les tonalités mineures aux débutants.' },
      { q: 'Ré mineur dans quelle musique ?', a: 'Ré mineur est présent dans énormément de chansons pop, rock et folk. Il est l\'accord relatif mineur de Fa majeur, ce qui le rend très courant dans les progressions Do–Fa–Sol–Ré mineur.' },
    ],
  },
  {
    slug: 'mi-mineur',
    symbol: 'Em',
    frenchName: 'Mi mineur',
    root: 'E',
    quality: 'mineur',
    notes: ['E', 'G', 'B'],
    frenchNotes: ['Mi', 'Sol', 'Si'],
    relatedSlugs: ['sol-majeur', 're-majeur', 'do-majeur', 'la-mineur'],
    description: 'Accord de Mi mineur : notes Mi–Sol–Si. Le plus facile de tous les accords, seulement 2 doigts.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Mi mineur ?', a: 'Mi mineur est formé de Mi (E), Sol (G) et Si (B). Avec seulement 2 doigts à la guitare, c\'est l\'accord le plus simple à apprendre tout en sonnant très bien sur les 6 cordes.' },
      { q: 'Comment jouer Mi mineur à la guitare ?', a: 'Mi mineur : posez simplement le majeur sur la corde La (2e frette) et l\'annulaire sur la corde Ré (2e frette). Toutes les 6 cordes sonnent à vide ou avec ces deux doigts. Parfait pour commencer.' },
      { q: 'Quel est le lien entre Mi mineur et Sol majeur ?', a: 'Mi mineur est le relatif mineur de Sol majeur : ils partagent exactement les mêmes notes (Sol, La, Si, Do, Ré, Mi). C\'est pourquoi ces deux accords sonnent si bien ensemble.' },
      { q: 'Mi mineur est-il adapté à la guitare acoustique ?', a: 'Mi mineur est l\'accord de prédilection pour la guitare acoustique. Son spectre complet (6 cordes) produit une résonance riche, parfaite pour les arpèges et le fingerpicking.' },
    ],
  },
  {
    slug: 'fa-mineur',
    symbol: 'Fm',
    frenchName: 'Fa mineur',
    root: 'F',
    quality: 'mineur',
    notes: ['F', 'Ab', 'C'],
    frenchNotes: ['Fa', 'La♭', 'Do'],
    relatedSlugs: ['lab-majeur', 'do-mineur', 'reb-majeur', 'fa-majeur'],
    description: 'Accord de Fa mineur : notes Fa–La♭–Do, diagramme guitare (barré 1re frette) et piano.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Fa mineur ?', a: 'Fa mineur est formé de Fa (F), La♭ (Ab) et Do (C). Le La♭ (tierce mineure) lui donne un caractère plus sombre que Fa majeur.' },
      { q: 'Comment jouer Fa mineur à la guitare ?', a: 'Fa mineur nécessite un barré complet à la 1re frette (forme de Mi mineur transposée). C\'est un accord qui combine le défi du barré de Fa majeur avec la sonorité plus dramatique du mineur.' },
      { q: 'Fa mineur est-il utilisé dans le classique ?', a: 'Fa mineur est une tonalité associée à la musique dramatique. Chopin a composé plusieurs pièces célèbres en Fa mineur, notamment des préludes et nocturnes à l\'atmosphère sombre et tragique.' },
      { q: 'Quelle relation entre Fa mineur et La♭ majeur ?', a: 'Fa mineur est le relatif mineur de La♭ majeur. Ils partagent les mêmes 3 bémols à la clé (Si♭, Mi♭, La♭). Ces deux accords fonctionnent naturellement ensemble.' },
    ],
  },
  {
    slug: 'sol-mineur',
    symbol: 'Gm',
    frenchName: 'Sol mineur',
    root: 'G',
    quality: 'mineur',
    notes: ['G', 'Bb', 'D'],
    frenchNotes: ['Sol', 'Si♭', 'Ré'],
    relatedSlugs: ['sib-majeur', 'do-mineur', 're-mineur', 'fa-majeur'],
    description: 'Accord de Sol mineur : notes Sol–Si♭–Ré, diagramme guitare (barré 3e frette) et piano.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Sol mineur ?', a: 'Sol mineur est formé de Sol (G), Si♭ (Bb) et Ré (D). Le Si♭ (à la place du Si naturel de Sol majeur) crée ce caractère sombre et mélancolique.' },
      { q: 'Comment jouer Sol mineur à la guitare ?', a: 'Sol mineur se joue en barré à la 3e frette sur la forme de Mi mineur. C\'est l\'une des formes de barré les plus utilisées pour les accords mineurs.' },
      { q: 'Sol mineur est-il courant dans la musique funk et soul ?', a: 'Oui, Sol mineur est très présent dans le funk, le soul et le R&B. La progression Sol mineur – Do mineur – Ré majeur est l\'une des progressions les plus utilisées dans ces genres.' },
      { q: 'Quelle est la différence émotionnelle entre Sol majeur et Sol mineur ?', a: 'Sol majeur évoque la joie et l\'ouverture. Sol mineur, grâce au Si♭, prend une couleur nostalgique et dramatique. Ce changement d\'un seul demi-ton transforme radicalement l\'atmosphère.' },
    ],
  },
  {
    slug: 'la-mineur',
    symbol: 'Am',
    frenchName: 'La mineur',
    root: 'A',
    quality: 'mineur',
    notes: ['A', 'C', 'E'],
    frenchNotes: ['La', 'Do', 'Mi'],
    relatedSlugs: ['do-majeur', 'fa-majeur', 'sol-majeur', 'mi-mineur'],
    description: 'Accord de La mineur : notes La–Do–Mi. Le relatif mineur de Do majeur, incontournable en musique.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de La mineur ?', a: 'La mineur est formé de La (A), Do (C) et Mi (E). Le Do naturel (au lieu de Do# dans La majeur) lui confère sa sonorité mélancolique et expressive.' },
      { q: 'Comment jouer La mineur à la guitare ?', a: 'La mineur est l\'un des premiers accords appris : index sur Si (1re frette), majeur sur Sol (2e frette), annulaire sur Ré (2e frette). Les cordes La grave et Mi peuvent sonner à vide.' },
      { q: 'Pourquoi dit-on que La mineur est le relatif de Do majeur ?', a: 'La mineur et Do majeur partagent exactement les mêmes notes (Do, Ré, Mi, Fa, Sol, La, Si) — aucun dièse ni bémol. Ce sont deux tonalités sœurs, l\'une majeure, l\'autre mineure.' },
      { q: 'La mineur est-il utilisé dans le flamenco ?', a: 'La mineur (et la gamme de La phrygien) est au cœur du flamenco. La progression La mineur – Sol – Fa – Mi est l\'une des cadences les plus emblématiques de la musique espagnole.' },
    ],
  },
  {
    slug: 'si-mineur',
    symbol: 'Bm',
    frenchName: 'Si mineur',
    root: 'B',
    quality: 'mineur',
    notes: ['B', 'D', 'F#'],
    frenchNotes: ['Si', 'Ré', 'Fa#'],
    relatedSlugs: ['re-majeur', 'sol-majeur', 'fad-majeur', 'mi-mineur'],
    description: 'Accord de Si mineur : notes Si–Ré–Fa#, diagramme guitare (barré 2e frette) et piano.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Si mineur ?', a: 'Si mineur est formé de Si (B), Ré (D) et Fa# (F#). C\'est le relatif mineur de Ré majeur, très courant dans les chansons folk et rock en tonalité de Ré.' },
      { q: 'Comment jouer Si mineur à la guitare ?', a: 'Si mineur se joue en barré à la 2e frette sur la forme de La mineur (5 cordes). C\'est souvent l\'un des premiers barrés mineurs appris, légèrement plus accessible que Fa majeur car partiel.' },
      { q: 'Si mineur est-il facile pour les débutants ?', a: 'Le barré de Si mineur (2e frette) est moins tendu que Fa majeur (1re frette). C\'est souvent recommandé comme premier barré, mais il demande quand même de la pratique.' },
      { q: 'Dans quelles chansons entend-on Si mineur ?', a: 'Si mineur est très présent dans le rock acoustique et le folk. Il aparaît fréquemment avec Ré majeur, Sol majeur et La majeur dans des progressions populaires.' },
    ],
  },
  {
    slug: 'do-diese-mineur',
    symbol: 'C#m',
    frenchName: 'Do# mineur',
    root: 'C#',
    quality: 'mineur',
    notes: ['C#', 'E', 'G#'],
    frenchNotes: ['Do#', 'Mi', 'Sol#'],
    relatedSlugs: ['mi-majeur', 'la-majeur', 'fad-majeur', 'si-majeur'],
    description: 'Accord de Do# mineur : notes Do#–Mi–Sol#, barré 4e frette. Très utilisé dans la pop et le rock.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Do# mineur ?', a: 'Do# mineur (C#m) est formé de Do# (C#), Mi (E) et Sol# (G#). C\'est le relatif mineur de Mi majeur, l\'une des tonalités les plus populaires pour la guitare.' },
      { q: 'Comment jouer Do# mineur à la guitare ?', a: 'Do# mineur se joue en barré à la 4e frette sur la forme de La mineur. C\'est la même forme de barré que Si mineur, mais deux frettes plus haut.' },
      { q: 'Pourquoi Do# mineur est-il si présent dans la pop ?', a: 'La tonalité de La majeur, très utilisée en pop et rock, comporte Do# mineur comme accord III. On le retrouve dans d\'innombrables progressions populaires comme La–Fa#m–Ré–Mi ou La–Do#m–Fa#m–Mi.' },
      { q: 'Do# mineur et Ré♭ mineur, même accord ?', a: 'Oui, Do# mineur et Ré♭ mineur (Dbm) sont enharmoniquement équivalents. Ils désignent la même hauteur, juste notés différemment selon le contexte harmonique.' },
    ],
  },
  {
    slug: 'red-mineur',
    symbol: 'D#m',
    frenchName: 'Ré# mineur',
    root: 'D#',
    quality: 'mineur',
    notes: ['D#', 'F#', 'A#'],
    frenchNotes: ['Ré#', 'Fa#', 'La#'],
    relatedSlugs: ['sold-mineur', 'fad-majeur', 'si-majeur', 'solb-majeur'],
    description: 'Accord de Ré# mineur (Mi♭ mineur) : notes Ré#–Fa#–La#, diagramme guitare et piano.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Ré# mineur ?', a: 'Ré# mineur est formé de Ré# (D#), Fa# (F#) et La# (A#). Enharmoniquement identique à Mi♭ mineur (Ebm), formé de Mi♭, Sol♭ et Si♭.' },
      { q: 'Comment jouer Ré# mineur à la guitare ?', a: 'Ré# mineur / Mi♭ mineur se joue en barré à la 6e frette sur la forme de La mineur, ou on peut le jouer en position haute.' },
      { q: 'Dans quelles tonalités trouve-t-on Ré# mineur ?', a: 'Ré# mineur (Mi♭ mineur) apparaît comme accord relatif mineur de Fa# majeur (Sol♭ majeur), ainsi que dans des tonalités chromatiques souvent utilisées en jazz et en metal.' },
      { q: 'Ré# mineur est-il rare dans la musique populaire ?', a: 'Ré# mineur est moins courant que Do# ou Si mineur, mais on le rencontre dans le metal progressif, le jazz et certains morceaux de pop qui cherchent des couleurs harmoniques inhabituelles.' },
    ],
  },
  {
    slug: 'fad-mineur',
    symbol: 'F#m',
    frenchName: 'Fa# mineur',
    root: 'F#',
    quality: 'mineur',
    notes: ['F#', 'A', 'C#'],
    frenchNotes: ['Fa#', 'La', 'Do#'],
    relatedSlugs: ['la-majeur', 're-majeur', 'si-mineur', 'do-diese-mineur'],
    description: 'Accord de Fa# mineur : notes Fa#–La–Do#. Le relatif mineur de La majeur, omniprésent en pop et rock.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Fa# mineur ?', a: 'Fa# mineur est formé de Fa# (F#), La (A) et Do# (C#). Il est le relatif mineur de La majeur et partage exactement les mêmes notes dans sa gamme.' },
      { q: 'Comment jouer Fa# mineur à la guitare ?', a: 'Fa# mineur se joue en barré à la 2e frette sur la forme de Mi mineur. C\'est l\'un des barrés les plus courants, souvent parmi les premiers appris car utilisé dans de nombreuses chansons.' },
      { q: 'Fa# mineur est-il présent dans beaucoup de chansons ?', a: 'Oui, Fa# mineur est extrêmement courant. La progression La–Fa#m–Ré–Mi est l\'une des plus utilisées dans la pop mondiale. On l\'entend dans des centaines de tubes.' },
      { q: 'Quelle est la différence entre Fa# mineur et Fa# majeur ?', a: 'Fa# mineur a un La naturel comme tierce, donnant une couleur sombre. Fa# majeur a un La# (tierce majeure), sonnant plus lumineux et moins courant dans la pop.' },
    ],
  },
  {
    slug: 'sold-mineur',
    symbol: 'G#m',
    frenchName: 'Sol# mineur',
    root: 'G#',
    quality: 'mineur',
    notes: ['G#', 'B', 'D#'],
    frenchNotes: ['Sol#', 'Si', 'Ré#'],
    relatedSlugs: ['si-majeur', 'mi-majeur', 'do-diese-mineur', 'red-mineur'],
    description: 'Accord de Sol# mineur (La♭ mineur) : notes Sol#–Si–Ré#, barré 4e frette.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de Sol# mineur ?', a: 'Sol# mineur est formé de Sol# (G#), Si (B) et Ré# (D#). Enharmoniquement équivalent à La♭ mineur (Ab, C♭/B, E♭). Il est le relatif mineur de Si majeur.' },
      { q: 'Comment jouer Sol# mineur à la guitare ?', a: 'Sol# mineur se joue en barré à la 4e frette sur la forme de Mi mineur. C\'est la même forme que Fa# mineur (2e frette) et Si mineur (7e frette), juste deux frettes plus haut que Fa# mineur.' },
      { q: 'Dans quelles tonalités apparaît Sol# mineur ?', a: 'Sol# mineur (La♭ mineur) est le relatif mineur de Si majeur. Il apparaît aussi comme accord III dans Mi majeur. On le retrouve dans des morceaux en Mi ou Si, typiques du rock et de la pop.' },
      { q: 'Sol# mineur est-il difficile à la guitare ?', a: 'Sol# mineur utilise un barré à la 4e frette, ce qui est plus confortable qu\'à la 1re ou 2e frette. Une fois la forme de Mi mineur maîtrisée, il s\'apprend assez rapidement.' },
    ],
  },
  {
    slug: 'lad-mineur',
    symbol: 'A#m',
    frenchName: 'La# mineur',
    root: 'A#',
    quality: 'mineur',
    notes: ['A#', 'C#', 'F'],
    frenchNotes: ['La#', 'Do#', 'Fa'],
    relatedSlugs: ['reb-majeur', 'sold-mineur', 'fad-mineur', 'sib-majeur'],
    description: 'Accord de La# mineur (Si♭ mineur) : notes La#–Do#–Fa, diagramme guitare et piano.',
    faqItems: [
      { q: 'Quelles notes composent l\'accord de La# mineur ?', a: 'La# mineur (A#m) est formé de La# (A#), Do# (C#) et Fa (F). Son équivalent enharmonique Si♭ mineur (Bbm) est formé de Si♭ (Bb), Ré♭ (Db) et Fa (F).' },
      { q: 'Comment jouer La# mineur à la guitare ?', a: 'La# mineur (Si♭ mineur) se joue en barré à la 1re frette sur la forme de La mineur. C\'est un barré partiel sur 5 cordes (forme Am barrée), souvent plus facile à appréhender que Fm ou Bbm.' },
      { q: 'La# mineur est-il courant dans la musique classique ?', a: 'Si♭ mineur est une tonalité que Chopin affectionnait pour ses pièces dramatiques. On trouve aussi ce relatif mineur dans des compositions romantiques associées à la gravité et à l\'introspection.' },
      { q: 'La# mineur / Si♭ mineur, lequel utiliser ?', a: 'Les deux désignent le même accord. Si♭ mineur (Bbm) est plus courant en notation pour les partitions avec bémols. La# mineur (A#m) apparaît dans les contextes avec dièses. ChordFinder peut afficher les deux.' },
    ],
  },
];

export function getChordBySlug(slug: string): ChordPageData | undefined {
  return CHORD_PAGES.find((c) => c.slug === slug);
}

export function getRelatedChords(chord: ChordPageData): ChordPageData[] {
  return chord.relatedSlugs
    .map((slug) => CHORD_PAGES.find((c) => c.slug === slug))
    .filter((c): c is ChordPageData => c !== undefined);
}
